### ISSUE TITLE
0.0.5 have invisible borders

### ISSUE THREAD

**Issue by tifandotme** [th0jensen/gruber-darker.zed#4]
I just synced my fork and found that some elements are now invisible (including the borders). I don't understand this change: https://github.com/th0jensen/gruber-darker.zed/commit/f63442e67d7aba1a4c5aa4a2e59b5c95c3a8128e

<img width="1680" alt="Screenshot 2024-12-01 at 17 58 15" src="https://github.com/user-attachments/assets/6017addc-6969-48ae-abfd-ce8e2cd3cfc1">

May I ask why some colors are changed to #191919?

**Comment by th0jensen** [comment]
It was added purely as personal preference, but since I added it I found  it to be confusing at times... here's what I'll do: Provide 2 theme files, one of your fork (with the theme <0.0.5) and one file that has the "cleaner" look without the borders.

**Comment by th0jensen** [comment]
Added a PR now, would you take a look at it and let me know if there's some more I should change? :) @tifandotme

**Comment by tifandotme** [comment]
@th0jensen I added some comments to the PR.

Great idea to have to 2 different theme. Personally, I like the UI sections to be separated and distinctive.

**Comment by th0jensen** [comment]
Made it into 3 themes. One standard, one minimal, and one dimmed (with grayed out comments). I'll get v0.0.6 merged into zed-extensions asap :)
